/* ============================================================
   OPERATION BIRTHDAY — mammacita / Quinn / Star
   From: Dzaddzzzy  (Pablo / Taku)
   Edit messages here. Drop photos as 01.jpg, 02.jpg, ...
   in Assets/images/{funny,flirty,romantic,us,randoms}
   Videos: Assets/videos/intro/dance.mp4
           Assets/videos/final/surprise.mp4
   Chats:  Assets/chats/01.jpg  (we'll turn screenshots into bubbles)
   Preview before 21 Sept: add ?preview=1 to the URL
   ============================================================ */

window.BDAY = {
  her: {
    name: "Charity",
    call: "mammacita",
    nicknames: [ "Quinn", "Star"],
    full: "Charity Magawagawa",
  },
  flirtyPass: "forever",
  him: {
    names: ["Pablo", "Taku"],
    from: "Dzaddzzzy",
    surname: "Magawagawa",
  },
  ages: { him: 23, her: 22 },
  pin: "2322", // his age + her age. switch to "2223" if you want her-first
  birthdayISO: "2026-09-21",
  capsuleISO: "2026-10-21",
  whatsappNumber: "", // e.g. "2637XXXXXXX" no plus. empty = copy text instead
  dateTitle: "Date with Dzaddzzzy",
  dateDetails: "TBD — he will fill this in.",

  slots: {
    funny: 6,
    flirty: 5,
    romantic: 6,
    us: 8,
    randoms: 9,
    finale: 1,
  },

  copy: {
    dossier: {
      lines: [
        "CLASSIFIED — OPERATION BIRTHDAY",
        "SUBJECT: Charity Magawagawa",
        "ALIASES: · Quinn · Star",
        "FROM: Dzaddzzzy",
        "CHARM .............. 98%",
        "ATTITUDE ........... 1000%",
        "PATIENCE WITH HIM .. 12%",
        "DANCE SKILL ........ under investigation",
        "WHY LOVABLE ....... PROLLY VODOO",
        "THREAT LEVEL ....... dangerously cute",
      ],
      loading: ["Downloading chaos…", "14%", "69%", "100%"],
    },
    cookie: {
      text: "This site uses cookies. Mostly for me.",
      accept: "Accept",
      also: "Also accept",
    },
    terms: {
      a: "I agree Dzaddzzzy is the funniest person alive",
      b: "I am smiling already",
      continue: "Continue",
    },
    prestart: {
      line: "Take this seriously it took me 3 months to make this",
      button: "continue",
    },
    hey: ["Hey you…", "Yes, YOU.", "I have something for you."],
    boomTitle: "HAPPY BIRTHDAY, BEAUTIFUL",
    boomSub: "Charity Magawagawa",
    freeze: [
      "I USE THE SURNAME I GIVE YOU",
       "Okay… enough of the serious stuff.",
        "Let's get this partyyyyyy started."
    ],
    danceBuild: [
      "Every good birthday party needs…",
      "…someone who knows how to dance.",
      "And unfortunately…",
      "…we have HER.",
    ],
    callName: "Meu Esapgou ",
    callDecline: "you can't decline me.",
    danceStickers: [
      "THE GUEST OF HONOR HAS ENTERED",
      "security, she is too fine",
      "birthday behaviour already?",
      "Okayyyy girl",
      "LET'S GET THE PARTY STARTED",
    ],
    danceAfter: [
      "I would like to report a public disturbance.",
      "That was illegal. I'm calling your mom.",
      "Anyways. Serious question.",
    ],
    loveQ: "DO YOU LOVE ME?",
    noLines: [
      "Are you sure?",
      "Eeeeeegh… try again.",
      "You really woke up and chose violence today",
      "Girl… be serious.",
      "You're fighting a losing battle",
      "I'm deleting the NO button.",
      "That's cute.",
      "You thought this was democracy?",
      "Wrong answer.",
      "I admire the confidence.",
      "Nice try.",
      "Yeah, I didn't think so.",
    ],
    yesInstant: "No hesitationd dayummnnnn. Screenshotting that.",
    universe: "The universe has spoken.",
    muchBetter: "Much better, kasaskammm.",
    captchaTitle: "Verify you're human",
    captchaTask: "Select all images containing the most beautiful girl.",
    captchaIncomplete: "incomplete.",
    captchaWrong: "Nope. That's not mammacita.",
    captchaCorrectTroll: [
      "nagh u clearly knoe tt aint her go again girl",
      "you thought i'd let you pass that fast? run it back.",
      "too smooth. prove it one more time, detective.",
    ],
    captchaCorrectPass: [
      "now tts my gal you didnt give in to that fake stuff :)",
      "see? standards. that's my mammacita 😌",
      "approved. taste level = elite.",
    ],
    captchaWrongOnly: [
      "what do u think you have done, you think Marsai stands a chance against u ..Grow up Gal ..NOW L SAID WHO IS THE MOST BEAUTIFUL GIRL IN THE WORLD   choose my gal uko ziguma",
      "seriously babe u really thought you are not the most gojas gal l have seen ....l'm dissapointed ",
      "all decoys again? are you trolling me or yourself.",
      "final warning before i report this kuna Mbuya Magawa🚨",
    ],
    captchaAllPics: [
      "Handitambe newe Charity",
      "ahh now you're choosing everyone? this isn't group work. choose only my gal",
      "still picking all of them? focus babe, only mammacita",
      "you clicked everybody like it's attendance. try again.",
      "respectfully, this is not a democracy ballot.",
    ],
    captchaMixed: [
      "no half-half babe. only the prettiest.",
      "nice try blending truths and lies, hollywood villain.",
      "mixed picks again? i expected better judgement, counselor.",
    ],
    captchaMissedHer: [
      "look again and she says i am the one with closed eyes",
      "still missing one. all her pics, none of the other.",
      "close but no cake one queen still unpicked.",
      "you missed her again? open both eyes this time.",
    ],
    captchaNone: [
      "pick something first, detective.",
      "standing there doing nothing won't unlock this.",
      "hello? tap the photos, not my patience.",
    ],
    captchaRageTitle: "RAGE MODE ACTIVATED",
    captchaRageTask: "NOW l SAID WHO IS THE MOST BEAUTIFUL GIRL IN THE WORLD",
    captchaRageIntro: [
      "Aight Ndokumamisa Charity ",
      "we are not leaving this screen until you choose my gal properly and now u owe me.",
    ],
    captchaRageFail: [
      "still wrong in rage mode? are we fighting or reading.",
      "this is now a full investigation.Nxaa choose only boo.",
      "last warning before i lock this app for emotional damage and trust me u wont access it again.",
    ],
    captchaRageCorrect: "there we go.Dont forget to apologise in my dm, proceed my nailtech💅",
    captchaOk: "verified. obviously.",
    locationAsk: "This site wants to access your location.",
    locationReason: "Reason: to find you.",
    locationFound: "Location found: inside my heart.",
    pinIntro: ["Good answer.", "But…", "You haven't unlocked the rest yet."],
    pinFakeHint: "Hint: it's the year you became annoying.",
    pinWrong: [
      "Hmm… nope",
      "I'm starting to question everything.",
      "Girl",
      "I knew you were gonna fumble that.",
      "Eeeegh srsly, You had ONE job.",
    ],
    pinHelp: ["Need help?", "No.", "Figure it out.", "…okay fine."],
    pinReal: ["Fine. Since apparently I have to help you…", "MY AGE + YOUR AGE", "Put them together."],
    pinOk: ["Finally!", "I knew you could do it.", "Come on… let's look at some memories."],
    hubTitle: "Four sides of you.",
    hubSub: "Choose your adventure.",
    rooms: {
      funny: {
        title: "FUNNY",
        tag: "evidence you can't be serious",
        lines: [
          "Evidence that you have absolutely no sense.",
          "Why were you like this?",
          "I still cannot explain this picture.",
          "Haa l am judging ini.",
          "I kept this one for blackmail. Happy birthday.",
          "Yea… let's move on.",
        ],
        stamp: "ROOM CLEARED — chaos archived",
      },
      flirty: {
        title: "FLIRTY",
        tag: "do not show your father",
        locked: "LOCKED ...3 keys, then one more word.",
        lines: [
          "Okay… now let's talk about how sexxxxxy you are.",
          "Actually… I might be slightly obsessed.",
          "Slightly.",
          "Okay fine. Very.",
          "My sexy booger.",
          "Staring is rude. Keep going.",
          "If you ask if you look good, the answer is yes. Next slide.",
        ],
        stamp: "ROOM CLEARED — classified",
      },
      romantic: {
        title: "ROMANTIC",
        tag: "okay I'll behave… a little",
        lines: [
          "Some moments just stay with you.",
          "Some people make ordinary days feel different.",
          "And somehow, you became one of my favourite parts of mine.",
          "This is the part where I get soft. Don't tell anyone.",
          "I'd pick this version of you in every universe.",
          "Come closer. The photo already did.",
        ],
        stamp: "ROOM CLEARED — heart noted",
      },
      us: {
        title: "US",
        tag: "exhibit: our love belongs in a movie scene.",
        lines: [
          "Look how many memories we've already made.",
          "And somehow…",
          "…I still want more.",
          "Proof we exist.",
          "We are actually cute.",
          "Timestamp: I already liked you here.",
          "If this was a movie they'd say we peaked. They would be wrong.",
        ],
        stamp: "ROOM CLEARED — more please",
      },
    },
    rotate: "Turn your phone sideways for this one.",
    rotateSkip: "I can't rotate",
    giftWait: ["Okay…", "I have one last thing for you.", "Don't get too excited."],
    giftFake: ["WAIT.", "You thought it was that easy?"],
    giftHold: "Don't let go.",
    giftAlmost: "We were so close.",
    scan: ["Scanning how much I like you…", "ERROR: number too large for this cheap website"],
    finaleCaption: "I saved my favourite for last.",
    letter: [
      "mammacita.",
      "I made this because cake is boring and you are not.",
      "You're annoying in the specific way I want every day.",
      "I like the version of you that laughs too loud, dances like the room is yours, and still somehow fits in my chest like a secret.",
      "Happy birthday, mammacita.",
      "Now stop looking at me like that. I planned this.",
    ],
    letterSign: ["Always,", "Taku"],
    candles: "Blow.",
    candlesDeny: "Fine. Swipe them out, coward.",
    secretHearts: [
      "You found one",
      "Okay, you're actually paying attention.",
      "Fine. Here's another one",
      "Star. Slow down.",
      "You found them all.",
    ],
    secretAll: "You found every heart. That's so you.",
    tabLeave: "I saw you leave. Who were you texting.",
    idle: "Hello? Did you fall asleep on my masterpiece?",
    idleWatch: [
      "You still there?",
      "mammacita…",
      "I know you're reading this.",
      "Stop pretending you're not impressed.",
    ],
    callDeclineLines: [
      "Why are you declining your birthday entertainment?",
      "Decline again. I dare you.",
      "Ndokurova Charity.",
      "Fine. Keep running from fun.",
    ],
    cakeEgg: [
      "Why are you touching the cake?",
      "Seriously?",
      "Fine.",
    ],
    pinGranted: "ACCESS GRANTED",
    pinOverride: "SYSTEM OVERRIDE",
    chapters: {
      funny: { num: "01", title: "CHAOS ARCHIVE", sub: "evidence you can't be serious" },
      romantic: { num: "02", title: "SOFT MODE", sub: "okay I'll behave… a little" },
      us: { num: "03", title: "OUR TIMELINE", sub: "exhibit: we're actually cute" },
      flirty: { num: "04", title: "DANGER ZONE", sub: "do not show your father" },
      finale: { num: "05", title: "THE FINALE", sub: "this is why you matter" },
    },
    hubComplete: "You found all four sides of us.",
    capsuleMystery: "One last thing isn't ready yet. Come back.",
    capsuleDays: (n) => `${n} day${n === 1 ? "" : "s"} remaining`,
    datePhases: {
      before: "Something is waiting for you…",
      today: "Today's the day.",
      after: "You made it past the lock. Good.",
      capsule: "CAPSULE UNLOCKED",
    },
    directorsCut: {
      wait: "Wait…",
      survived: "You survived.",
      btn: "WATCH DIRECTOR'S CUT",
      lines: [
        "funniest photo — still evidence",
        "dance clip — public disturbance",
        "funniest message — archived",
        "one hidden photo — classified",
        "secret message — you earned this",
      ],
    },
    mascot: {
      default: "♥",
      no: "She's still trying.",
      pin: "I gave her the hint…",
      yes: "Called it.",
      flirty: "Don't get shy now.",
      end: "I told you she'd like it.",
    },
    receiptReport: {
      title: "CHARITY'S BIRTHDAY REPORT",
      love: "100%",
      cooperation: "Questionable",
      flirting: "Dangerous",
      overall: "Approved",
      pinIntel: "Needs improvement",
    },
    late: "It's late and you're on my website. Interesting.",
    welcomeBack: "Oh. You came back.",
    missed: "I knew you'd miss it.",
    end: ["That's it. I ran out of website.", "If you cried, I win.", "If you didn't, open the flirty room again."],
    theEnd: "THE END…?",
    orIsIt: "Or is it?",
    capsuleLock: "LOCKED. Unlocks 21 October. Yes, I planned that far ahead. Yes, I'm like this.",
    capsulePeek: [
      "Mamma",
      "If you're reading this, I really did plan 30 days ahead.",
      "Part two goes here.",
      "Maybe sum' will appear after 30 days or l just want you to wait for nonsense. Don't forget.",
    ],
    noGhost: [
      "don't tell him I'm here",
      "worst day of my life",
      "I was a button once",
    ],
    blooper: "BLOOPERS — you tapped the name like you were looking for trouble.",
    shareTitle: "Quinn survived Operation Birthday",
    shareSub: "Issued by ur manssss. No refunds.",
    flirtyGate: {
      prompt: "together",
      hint: "finish it.",
      placeholder: "the rest…",
      go: "unlock",
      wrong: [
        "not that.",
        "you know this one.",
        "together…?",
      ],
      help: "the word that comes after.",
      ok: "together forever.",
    },
  },

  chats: [
    {
      when: "then",
      bubbles: [
        { who: "him", text: "you're ignoring me" },
        { who: "her", text: "I'm literally in the same room" },
        { who: "him", text: "so look at me" },
        { who: "her", text: "…" },
        { who: "him", text: "that's what I thought, Starrr" },
      ],
    },
    {
      when: "later",
      bubbles: [
        { who: "her", text: "Quinn is not talking to you" },
        { who: "him", text: "tell Quinn Dzaddzzzy said hi" },
        { who: "her", text: "she said you're annoying" },
        { who: "him", text: "she loves it" },
      ],
    },
  ],
};
