/* ============================================================
   OPERATION BIRTHDAY — mammacita / Quinn / Star
   From: Dzaddzzzy  (Pablo / Taku)
   Edit messages here. Media can be named like:
   1...caption text.JPG, 2...caption text.jpg, etc.
   in Assets/images/{funny,flirty,romantic,us,videocall}
   Videos: Assets/videos/intro/dance.mp4
           Assets/videos/final/surprise.mp4
   Chats:  Assets/chats/01.jpg  (we'll turn screenshots into bubbles)
   Preview before 21 Sept: add ?preview=1 to the URL
   ============================================================ */

window.BDAY = {
  her: {
    name: "Charity",
    call: "mammacita",
    nicknames: [ "Quinn", "Star"],
    full: "Charity Magawagawa",
  },
  flirtyPass: "forever",
  him: {
    names: ["Pablo", "Taku"],
    from: "Dzaddzzzy",
    surname: "Magawagawa",
  },
  ages: { him: 23, her: 22 },
  pin: "2322", // his age + her age. switch to "2223" if you want her-first
  birthdayISO: "2026-09-21",
  capsuleISO: "2026-10-21",
  whatsappNumber: "", // e.g. "2637XXXXXXX" no plus. empty = copy text instead
  dateTitle: "Date with Dzaddzzzy",
  dateDetails: "TBD — he will fill this in.",

  slots: {
    funny: 9,
    flirty: 9,
    romantic: 7,
    us: 10,
    randoms: 9,
    finale: 1,
  },

  media: {
    funny: [
      "1..yea just imagine this is the woman of my dreamsss.jpg",
      "2...she can sleep yoo.JPG",
      "3...l said she can sleep imiee.JPG",
      "4...ya are not hearing me this one can .....JPG",
      "5...ye l knoe what u wld hv said ska huya hko on top.jpg",
      "6...donno where she got this from.jpg",
      "7...yes this.PNG",
      "8...bombastic what what...JPG",
      "9..with all said she loves me enough to forget about cancerrr.jpg",
    ],
    romantic: [
      "1...damn the prettiest birthday gal you will ever see.JPG",
      "2...give it up for my blushing birthday quinnnnnn.JPG",
      "3... shez hella gorgeous did l tell you.jpg",
      "4... you are loved mamma, keep aging like wine.jpg",
      "5...oogh sorry wrong category.JPG",
      "6... shez profesionally smart too.JPG",
      "7..babie wangu akanaka.jpg",
    ],
    flirty: [
      "1...lets kick this off with a mwaaa.JPG",
      "2...and another one for my very dry lipsss.JPG",
      "3... yo yo yo too fast forgot this is PG... also donno where the clothes are.JPG",
      "4..ok lets cuddle now buh damn look at tt leg.JPG",
      "5...lemme give u another angle of the leg zhhhhhhh.JPG",
      "6....Proverbs 5 vs 19.png",
      "7...and the burrrrrrrrrrrtttttyyyy aagh horaiti byeee.png",
      "8..the butty snaps l used to get (crying emoji).jpg",
      "9...damn cld get some sexy picsssss.jpg",
    ],
    us: [
      "1..our love was always written in the stars.png",
      "2...That look tt makes me rethink wah l was doing with my life before her.png",
      "3...l knoe l knoe just move on to the next.png",
      "4... this is just beautiful birthday gal never let it go.JPG",
      "5....keep holding it like this.JPG",
      "6...you cant go wrong with this one.png",
      "7..shez the best.JPG",
      "8..look at these ladiesssss.PNG",
      "9... the smiles say it all.JPG",
      "10...till death do us apart.JPG",
    ],
    videocall: [
      "IMG_5627.JPG",
    ],
    favorite: [
      "IMG_2741.jpeg",
      "1.jpg",
    ],
    captchaHer: [
      "idf.jpg",
      "img2.jpg",
      "ed5673fa-7c06-4449-ad5b-e9f77ecc4130.jpg",
    ],
    captchaDecoys: [
      "marsai 1.jfif",
      "marsai 2.jfif",
      "marsai 3.jfif",
    ],
  },
  videos: {
    intro: "Assets/videos/intro/bafdae dance.mp4",
    finale: "Assets/videos/final/surprise.mp4",
  },

  copy: {
    dossier: {
      lines: [
        "CLASSIFIED — OPERATION BIRTHDAY",
        "SUBJECT: Charity Magawagawa",
        "ALIASES: · Quinn · Star",
        "FROM: Dzaddzzzy",
        "CHARM .............. 98%",
        "ATTITUDE ........... 1000%",
        "PATIENCE WITH HIM .. 12%",
        "DANCE SKILL ........ under investigation",
        "WHY LOVABLE ....... PROLLY VODOO",
        "THREAT LEVEL ....... dangerously cute",
      ],
      loading: ["Downloading chaos…", "14%", "69%", "100%"],
    },
    cookie: {
      text: "This site uses cookies. Mostly for me.",
      accept: "Accept",
      also: "Also accept",
    },
    terms: {
      a: "I agree Dzaddzzzy is the funniest person alive",
      b: "I am smiling already",
      continue: "Continue",
    },
    prestart: {
      line: "Take this seriously it took me 3 months to make this",
      button: "continue",
    },
    hey: ["Hey you…", "Yes, YOU.", "I have something for you."],
    boomTitle: "HAPPY BIRTHDAY, BEAUTIFUL",
    boomSub: "Charity Magawagawa",
    freeze: [
      "I USE THE SURNAME I GIVE YOU",
       "Okay… enough of the serious stuff.",
        "Let's get this partyyyyyy started."
    ],
    danceBuild: [
      "Every good birthday party needs…",
      "…someone who knows how to dance.",
      "And unfortunately…",
      "…we have HER.",
    ],
    callName: "Meu espaço seguro",
    callDecline: "you can't decline me.",
    danceStickers: [
      "THE GUEST OF HONOR HAS ENTERED",
      "security, she is too fine",
      "birthday behaviour already?",
      "Okayyyy girl",
      "LET'S GET THE PARTY STARTED",
    ],
    danceAfter: [
      "I would like to report a public disturbance.",
      "That was illegal. I'm calling your mom.",
      "Anyways. Serious question.",
    ],
    loveQ: "DO YOU LOVE ME?",
    noLines: [
      "Are you sure?",
      "Eeeeeegh… try again.",
      "You really woke up and chose violence today",
      "Girl… be serious.",
      "You're fighting a losing battle",
      "I'm deleting the NO button.",
      "That's cute.",
      "You thought this was democracy?",
      "Wrong answer.",
      "I admire the confidence.",
      "Nice try.",
      "Yeah, I didn't think so.",
    ],
    yesInstant: "No hesitationd dayummnnnn. Screenshotting that.",
    universe: "The universe has spoken.",
    muchBetter: "Much better, kasaskammm.",
    captchaTitle: "the most beautiful girl in the world",
    captchaTask: "Select the images with",
    captchaIncomplete: "incomplete.",
    captchaWrong: "Nope. That's not mammacita.",
    captchaCorrectTroll: [
      "nagh u clearly knoe tt aint her go again girl",
      "you thought i'd let you pass that fast? run it back.",
      "too smooth. prove it one more time, detective.",
    ],
    captchaCorrectPass: [
      "now tts my gal you didnt give in to that fake stuff :)",
      "see? standards. that's my mammacita 😌",
      "approved. taste level = elite.",
    ],
    captchaWrongOnly: [
      "what do u think you have done, you think Marsai stands a chance against u ..Grow up Gal ..NOW L SAID WHO IS THE MOST BEAUTIFUL GIRL IN THE WORLD   choose my gal uko ziguma",
      "seriously babe u really thought you are not the most gojas gal l have seen ....l'm dissapointed ",
      "all decoys again? are you trolling me or yourself.",
      "final warning before i report this kuna Mbuya Magawa🚨",
    ],
    captchaAllPics: [
      "Handitambe newe Charity",
      "ahh now you're choosing everyone? this isn't group work. choose only my gal",
      "still picking all of them? focus babe, only mammacita",
      "you clicked everybody like it's attendance. try again.",
      "respectfully, this is not a democracy ballot.",
    ],
    captchaMixed: [
      "no half-half babe. only the prettiest.",
      "nice try blending truths and lies, hollywood villain.",
      "mixed picks again? i expected better judgement, counselor.",
    ],
    captchaMissedHer: [
      "look again and she says i am the one with closed eyes",
      "still missing one. all her pics, none of the other.",
      "close but no cake one queen still unpicked.",
      "you missed her again? open both eyes this time.",
    ],
    captchaNone: [
      "pick something first, detective.",
      "standing there doing nothing won't unlock this.",
      "hello? tap the photos, not my patience.",
    ],
    captchaRageTitle: "RAGE MODE ACTIVATED",
    captchaRageTask: "NOW l SAID WHO IS THE MOST BEAUTIFUL GIRL IN THE WORLD",
    captchaRageIntro: [
      "Aight Ndokumamisa Charity ",
      "we are not leaving this screen until you choose my gal properly and now u owe me.",
    ],
    captchaRageFail: [
      "still wrong in rage mode? are we fighting or reading.",
      "this is now a full investigation.Nxaa choose only boo.",
      "last warning before i lock this app for emotional damage and trust me u wont access it again.",
    ],
    captchaRageCorrect: "there we go.Dont forget to apologise in my dm, proceed my nailtech💅",
    captchaOk: "verified. obviously.",
    locationAsk: "This site wants to access your location.",
    locationReason: "Reason: to find you.",
    locationFound: "Location found: inside my heart.",
    pinIntro: ["Good answer.", "But…", "You haven't unlocked the rest yet."],
    pinFakeHint: "Hint: it's the year you became annoying.",
    pinWrong: [
      "Hmm… nope",
      "I'm starting to question everything.",
      "Girl",
      "I knew you were gonna fumble that.",
      "Eeeegh srsly, You had ONE job.",
    ],
    pinHelp: ["Need help?", "No.", "Figure it out.", "…okay fine."],
    pinReal: ["Fine. Since apparently I have to help you…", "MY AGE + YOUR AGE", "Put them together."],
    pinOk: ["Finally!", "I knew you could do it.", "Come on… let's look at some memories."],
    hubTitle: "Four sides of you.",
    hubSub: "Choose a planet and travel.",
    rooms: {
      funny: {
        title: "FUNNY",
        tag: "evidence you can't be serious",
        lines: [
          "Evidence that you have absolutely no sense.",
          "Why were you like this?",
          "I still cannot explain this picture.",
          "Haa l am judging ini.",
          "I kept this one for blackmail. Happy birthday.",
          "Yea… let's move on.",
          "With all said she loves me enough to forget about cancer.",
        ],
        stamp: "ROOM CLEARED — chaos archived",
      },
      flirty: {
        title: "FLIRTY",
        tag: "do not show your father",
        locked: "LOCKED ...3 keys, then one more word.",
        lines: [
          "Okay… now let's talk about how sexxxxxy you are.",
          "Actually… I might be slightly obsessed.",
          "Slightly.",
          "Okay fine. Very.",
          "My sexy booger.",
          "Staring is rude. Keep going.",
          "If you ask if you look good, the answer is yes. Next slide.",
          "The butty snaps I used to get.",
          "Damn. Could get some sexy pics.",
        ],
        stamp: "ROOM CLEARED — classified",
      },
      romantic: {
        title: "ROMANTIC",
        tag: "okay I'll behave… a little",
        chatThreads: [
          {
            title: "convo 3",
            bubbles: [
              { who: "him", text: "4 naughty stuff u hv ever imagined me n u doin 👀" },
              { who: "her", text: "Giving each other massages tiri naked 🤭" },
              { who: "her", text: "Umm like pole dancing for each other wearing sexy stuff 💃" },
              { who: "her", text: "Then zvimwe takazviita" },
              { who: "her", text: "Eating yogurt from each other's bodies tiri mukitchen" },
              { who: "her", text: "Having sex mupool 😳" },
              { who: "him", text: "3 me,u moments u wont forget" },
              { who: "her", text: "The day you faked kundiramba ndikachema ndinewe 💔" },
              { who: "her", text: "The same day but the moments after crying when you assured me kuti you love me and you are here to stay also promising each other kuti we will resolve every conflict in our relationship hapana anorara akatsamwira umwe" },
              { who: "her", text: "the first day we talked this semester ❤️" },
              { who: "him", text: "2 words for me" },
              { who: "her", text: "You're amazing 🥺" },
              { who: "her", text: "I love you" },
              { who: "her", text: "I love you more babe" },
              { who: "him", text: "No me more" },
              { who: "her", text: "KY KY babe, I really appreciate you Taku ❤️" },
              { who: "her", text: "Love you soo much boo boo bear 🥹" },
              { who: "her", text: "I love you babe ❤️" },
              { who: "her", text: "May God protect you and may you be successful in all you do 🙏" },
              { who: "her", text: "Babe ❤️" },
            ],
          },
          {
            title: "convo 2",
            bubbles: [
              { who: "her", text: "Takudzwa....!!!!!!!" },
              { who: "him", text: "You know u e on girlfriend I hv opened up this much too" },
              { who: "her", text: "I know but I'm the only one for you babe, I'm your wife 🥺 we spending the rest of our lives together saka I must be your human diary" },
              { who: "her", text: "Apa ndadya orange my stomach now hurts 🍊" },
              { who: "him", text: "Mukadzi wangu iyeye 😂" },
              { who: "her", text: "iwe oranges apples anokwidza maacids manhi" },
              { who: "her", text: "Kasi ndiri dramatic 😂" },
              { who: "him", text: "Nopeee" },
            ],
          },
          {
            title: "convo 1",
            bubbles: [
              { who: "her", text: "hiiii Takudzwa ndozvandoita ini 😭" },
              { who: "him", text: "Wauchindiitei tiri ku discussion" },
              { who: "her", text: "iwe wanga uchidaro wani 😂" },
              { who: "her", text: "You were touching my bums 😭" },
              { who: "him", text: "Aaagh ska zhine basa" },
              { who: "her", text: "Saka ini ndakubatawo back zvine basa??" },
              { who: "him", text: "chaku turner on pane vanhu kasaskam" },
            ],
          },
        ],
        lines: [
          "Some moments just stay with you.",
          "Some people make ordinary days feel different.",
          "And somehow, you became one of my favourite parts of mine.",
          "This is the part where I get soft. Don't tell anyone.",
          "I'd pick this version of you in every universe.",
          "Come closer. The photo already did.",
          "Babie wangu akanaka.",
        ],
        stamp: "ROOM CLEARED — heart noted",
      },
      us: {
        title: "US",
        tag: "exhibit: our love belongs in a movie scene.",
        lines: [
          "Look how many memories we've already made.",
          "And somehow…",
          "…I still want more.",
          "Proof we exist.",
          "We are actually cute.",
          "Timestamp: I already liked you here.",
          "If this was a movie they'd say we peaked. They would be wrong.",
        ],
        stamp: "ROOM CLEARED — more please",
      },
    },
    rotate: "Turn your phone sideways for this one.",
    rotateSkip: "I can't rotate",
    giftWait: ["Okay…", "I have one last thing for you.", "Don't get too excited."],
    giftFake: ["WAIT.", "You thought it was that easy?"],
    giftHold: "Don't let go.",
    giftAlmost: "We were so close.",
    scan: ["Scanning how much I like you…", "ERROR: number too large for this cheap website"],
    finaleCaption: "and Jehovah then took the pen himself so he could write our magnificent love story",
    letter: [
      // Paste the royal birthday letter here when you have it. It scrolls like a scroll.
      "mammacita.",
      "I made this because cake is boring and you are not.",
      "You're annoying in the specific way I want every day.",
      "I like the version of you that laughs too loud, dances like the room is yours, and still somehow fits in my chest like a secret.",
      "Happy birthday, mammacita.",
      "Now stop looking at me like that. I planned this.",
    ],
    letterSign: ["Always,", "Taku"],
    candles: "Blow into your phone's mouthpiece.",
    candlesAsk: "Your phone will ask to use the microphone. Allow it, then blow into the mouthpiece.",
    candlesReady: "Blow into the mouthpiece. If nothing happens, swipe the flames.",
    candlesDeny: "Mic stayed off. Swipe the flames with your finger.",
    secretHearts: [
      "You found one",
      "Okay, you're actually paying attention.",
      "Fine. Here's another one",
      "Star. Slow down.",
      "You're collecting me now?",
      "Hidden on purpose. Keep going.",
      "Another one. Of course you found it.",
      "Okay this is getting impressive.",
      "Leave some mystery, mammacita.",
      "You're hunting hearts like rent is due.",
      "Still going? That's so you.",
      "Almost greedy. I like it.",
      "One more wouldn't hurt.",
      "You found them all.",
    ],
    secretAll: "You found every heart. That's so you.",
    tabLeave: "I saw you leave. Who were you texting.",
    idle: "Hello? Did you fall asleep on my masterpiece?",
    idleWatch: [
      "You still there?",
      "mammacita…",
      "I know you're reading this.",
      "Stop pretending you're not impressed.",
    ],
    callDeclineLines: [
      "Why are you declining your birthday entertainment?",
      "Decline again. I dare you.",
      "Ndokurova Charity.",
      "Fine. Keep running from fun.",
    ],
    cakeEgg: [
      "Why are you touching the cake?",
      "Seriously?",
      "Fine.",
    ],
    pinGranted: "ACCESS GRANTED",
    pinOverride: "SYSTEM OVERRIDE",
    chapters: {
      funny: { num: "01", title: "CHAOS ARCHIVE", sub: "evidence you can't be serious" },
      romantic: { num: "02", title: "SOFT MODE", sub: "okay I'll behave… a little" },
      us: { num: "03", title: "OUR TIMELINE", sub: "exhibit: we're actually cute" },
      flirty: { num: "04", title: "DANGER ZONE", sub: "do not show your father" },
      finale: { num: "05", title: "THE FINALE", sub: "this is why you matter" },
    },
    hubComplete: "Now you can print what happened.",
    hubNeedBoth: "The four sides are done. Now clear the sun, and the hourglass too.",
    hubNeedSun: "The sun is still waiting. Clear it first.",
    hubNeedCapsule: "The hourglass still needs you.",
    receiptDoor: "print the receipts",
    giftDoor: "one last thing",
    receiptBack: "back to the galaxy",
    movieCredits: [
      { role: "a Dzaddzzzy production", name: "OPERATION BIRTHDAY", big: true },
      { role: "starring", name: "mammacita" },
      { role: "also known as", name: "Charity Magawagawa" },
      { role: "and", name: "Quinn · Star" },
      { role: "written, directed and slightly unhinged by", name: "Taku" },
      { role: "reason", name: "cake is boring and you are not" },
      { role: "special thanks", name: "the version of you that laughs too loud" },
      { role: "also thanks", name: "dancing like the room is yours" },
      { role: "filed under", name: "fits in my chest like a secret" },
      { role: "message", name: "Happy birthday, mammacita." },
      { role: "postscript", name: "Now stop looking at me like that. I planned this." },
      { role: "issued to", name: "you, obviously" },
      { role: "no refunds", name: "THE END" , big: true },
    ],
    creditsEndTitle: "Happy birthday.",
    berserkerBtn: "go berserker",
    berserkerTitle: "BERSERKER",
    berserkerStop: "ok that's enough",
    berserkerStamps: [
      "Ngiyakutanda",
      "I love you",
      "Ndokuda",
      "Ndinokuda",
      "Je t'aime",
      "Te quiero",
      "Ich liebe dich",
      "Ti amo",
      "Eu te amo",
      "Wo ai ni",
      "Saranghae",
      "Mahal kita",
      "Aishiteru",
      "Ana uhibbuki",
      "Ngiyakuthanda",
      "I LOVE YOU",
    ],
    capsuleMystery: "One last thing isn't ready yet. Come back.",
    capsuleDays: (n) => `${n} day${n === 1 ? "" : "s"} remaining`,
    datePhases: {
      before: "Something is waiting for you…",
      today: "Today's the day.",
      after: "You made it past the lock. Good.",
      capsule: "CAPSULE UNLOCKED",
    },
    directorsCut: {
      wait: "Wait…",
      survived: "You survived.",
      btn: "WATCH DIRECTOR'S CUT",
      lines: [
        "funniest photo — still evidence",
        "dance clip — public disturbance",
        "funniest message — archived",
        "one hidden photo — classified",
        "secret message — you earned this",
      ],
    },
    mascot: {
      default: "♥",
      no: "She's still trying.",
      pin: "I gave her the hint…",
      yes: "Called it.",
      flirty: "Don't get shy now.",
      end: "I told you she'd like it.",
    },
    receiptReport: {
      title: "CHARITY'S BIRTHDAY REPORT",
      love: "100%",
      cooperation: "Questionable",
      flirting: "Dangerous",
      overall: "Approved",
      pinIntel: "Needs improvement",
    },
    late: "It's late and you're on my website. Interesting.",
    welcomeBack: "Oh. You came back.",
    missed: "I knew you'd miss it.",
    end: ["That's it. I ran out of website.", "If you cried, I win.", "If you didn't, open the flirty room again."],
    theEnd: "THE END…?",
    orIsIt: "Or is it?",
    capsuleLock: "LOCKED. Unlocks 21 October. Yes, I planned that far ahead. Yes, I'm like this.",
    capsulePeek: [
      "Mamma",
      "If you're reading this, I really did plan 30 days ahead.",
      "Part two goes here.",
      "Maybe sum' will appear after 30 days or l just want you to wait for nonsense. Don't forget.",
    ],
    noGhost: [
      "don't tell him I'm here",
      "worst day of my life",
      "I was a button once",
    ],
    blooper: "BLOOPERS — you tapped the name like you were looking for trouble.",
    shareTitle: "Quinn survived Operation Birthday",
    shareSub: "Issued by ur manssss. No refunds.",
    flirtyGate: {
      prompt: "TOGETHER",
      hint: "finish it.",
      placeholder: "the rest…",
      go: "unlock",
      wrong: [
        "not that.",
        "you know this one.",
      ],
      afterTwo: "when I say forever you say what",
      help: "when I say forever you say what",
      ok: "together forever.",
    },
  },

  chats: [
    {
      when: "then",
      bubbles: [
        { who: "him", text: "you're ignoring me" },
        { who: "her", text: "I'm literally in the same room" },
        { who: "him", text: "so look at me" },
        { who: "her", text: "…" },
        { who: "him", text: "that's what I thought, Starrr" },
      ],
    },
    {
      when: "later",
      bubbles: [
        { who: "her", text: "Quinn is not talking to you" },
        { who: "him", text: "tell Quinn Dzaddzzzy said hi" },
        { who: "her", text: "she said you're annoying" },
        { who: "him", text: "she loves it" },
      ],
    },
  ],
};
